#+title: Model parameterisation

This document contains derivation of the core model parameters used.
Note that the definition of the differential equations can be found in
the =sir_vacc= function in =ethics.model= (this is the function used
by =create-grid-database.py=).

#+begin_src R :session ethics :exports both
  library(glue)
  library(dplyr)
  library(ggplot2)
  gprint <- \(s) print(glue(s))
  gpasteprint <- \(ss) print(glue(paste(ss, collapse = "\n")))
#+end_src

#+RESULTS:

* Parameters from the literature

The population size an age group size is based off of Melbourne.

#+begin_src R :session ethics :exports both
  pop_size <- 5000000
  group_1_prop <- 0.89
  group_2_prop <- 1 - group_1_prop
#+end_src

#+RESULTS:
: 0.11

The average duration of a hospital stay as part of the clinical burden
comes from the average of a gamma distribution. These values are given
in Table 3.

#+begin_src R :session ethics :exports both
  average_hospital_stay_00_39 <- 2.27 * 0.95
  average_hospital_stay_40_69 <- 4.98 * 0.79
  average_hospital_stay_70_xx <- 7.32 * 1.04
#+end_src

#+RESULTS:
: 7.6128

Table 1 has the average /recovery period/ as 10.37 days. This gets
used in the estimate of the rate of removal from the infectious
compartment.

#+begin_src R :session ethics :exports both
  average_infectious_period <- 10.37
#+end_src

#+RESULTS:
: 10.37

The proportion hospitalised is for delta and omicron following the
reference given in the table.

#+begin_src R :session ethics :exports both
  prop_hospitalised <- list(age_under_70 = 0.0009, age_70_plus = 0.0378)
#+end_src

#+RESULTS:
| 0.0009 | 0.0378 |

** Demographic details from data ABS

#+begin_src R :session ethics :exports both
  age_sex_csv <- "./extrascripts/demographics/Australia_National_Age_and_Sex_2023.csv"
  age_sex_df <-
    age_sex_csv |>
    read.csv() |>
    rename(age = Age, num = N) |>
    select(age, num) |>
    group_by(age) |>
    summarise(total_num = sum(num))

  ## ggplot() +
  ##   geom_line(age_sex_df, mapping = aes(x = age, y = total_num)) +
  ##   theme_bw() +
  ##   labs(x = "Age", y = "Frequency")
  print(NULL)
#+end_src

#+RESULTS:

* Derived parameters                                                    :yes:

These values are for Australia as a whole. The proportion of the
national population below 70 is \(87.9\%\). The AIHW reports \(89\%\)
which is what we have used (as given in the configuration file).

#+begin_src R :session ethics :exports both
  group_1_size_aus <- sum(age_sex_df[age_sex_df$age < 70,]$total_num)
  group_2_size_aus <- sum(age_sex_df[age_sex_df$age >= 70,]$total_num)

  gpasteprint(c(
    "Australia:",
    paste0("Group 1 size ", group_1_size_aus),
    paste0("Group 2 size ", group_2_size_aus),
    paste0("Group 1 proportion ", group_1_size_aus / (group_1_size_aus + group_2_size_aus))
  ))
#+end_src

#+RESULTS:
| Australia:                           |
| Group 1 size 23426847                |
| Group 2 size 3232101                 |
| Group 1 proportion 0.878761119906157 |

We also need the proportion in the age ranges 0--39, 40--69 and 70+.

#+begin_src R :session ethics :exports both
  aus_0_39 <- sum(age_sex_df[age_sex_df$age < 40,]$total_num)
  aus_40_69 <- sum(age_sex_df[(40 <= age_sex_df$age) & (age_sex_df$age < 70),]$total_num)
  aus_70_plus <- sum(age_sex_df[age_sex_df$age >= 70,]$total_num)
  aus_total <- aus_0_39 + aus_40_69 + aus_70_plus
  aus_prop_0_39 <- aus_0_39 / aus_total
  aus_prop_40_69 <- aus_40_69 / aus_total
  aus_prop_70_plus <- aus_70_plus / aus_total

  gpasteprint(c(
    "Australia:",
    paste0("Age 0-39 size ", aus_0_39, " proportion ", aus_prop_0_39),
    paste0("Age 40-69 size ", aus_40_69, " proportion ", aus_prop_40_69),
    paste0("Age 70+ size ", aus_70_plus, " proportion ", aus_prop_70_plus)
  ))
#+end_src

#+RESULTS:
| Australia:                                          |
| Age 0-39 size 13978726 proportion 0.524353999265087 |
| Age 40-69 size 9448121 proportion 0.35440712064107  |
| Age 70+ size 3232101 proportion 0.121238880093843   |

#+begin_src R :session ethics :exports both
  group_1_size <- group_1_prop * pop_size
  group_2_size <- group_2_prop * pop_size

  gprint("Group 1 size {group_1_size}\nGroup 2 size {group_2_size}")
#+end_src

#+RESULTS:
| Group 1 size 4450000 |
| Group 2 size 550000  |

#+begin_src R :session ethics :exports both
  gamma_est <- 1 / average_infectious_period
  gprint("Estimated removal rate {gamma_est}")
#+end_src

#+RESULTS:
: Estimated removal rate 0.0964320154291225

People who are vaccinated but unprotected have the same dynamics as
those who are unvaccinated. For the vaccinated and protected people,
there is no infection possible. The /average hospital stay/ (measured
in days) is what we are using as out cost associated with infection.

#+begin_src R :session ethics :exports both
  group_1_avg_hosp_days_cond <-
    aus_prop_0_39 / (1 - aus_prop_70_plus) * average_hospital_stay_00_39 +
    aus_prop_40_69 / (1 - aus_prop_70_plus) * average_hospital_stay_40_69
  group_2_avg_hosp_days_cond <- average_hospital_stay_70_xx

  group_1_avg_hosp_days <- prop_hospitalised$age_under_70 * group_1_avg_hosp_days_cond
  group_2_avg_hosp_days <- prop_hospitalised$age_70_plus * group_2_avg_hosp_days_cond
  gprint("Group 1 average hospital stay {group_1_avg_hosp_days}\nGroup 2 average hospital stay {group_2_avg_hosp_days}")
#+end_src

#+RESULTS:
| Group 1 average hospital stay 0.00258610679582617 |
| Group 2 average hospital stay 0.28776384          |

* Summary table and links


| Parameter                     | Group 1 value | Group 2 value | Link   |
|-------------------------------+---------------+---------------+--------|
| Age range                     |          0-70 |           +70 |        |
| Population size, \(N_{i}\)    |     4,450,000 |       550,000 | [[file:./config/config-2024-10-14_manuscript.json::10][config]] |
| Removal rate, \(\gamma\)      |         0.125 |         0.125 | [[file:./config/config-2024-10-14_manuscript.json::8][config]] |
| Initially infected            |             1 |             1 | [[file:./config/config-2024-10-14_manuscript.json::36][config]] |
| Infection cost, \(C_{i}^{I}\) |       0.00259 |         0.288 |        |

The infection cost never appears in this way, it only appears as the
product of the probability of hospitalisation given infection (which
isn't group specific) and the expected number of days when
hospitalised (which is group specific).
